### ISSUE TITLE
Tag component warning

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#874]
For example: https://react-science.pages.dev/stories/?path=/story/components-button--with-tag

There is a warning even though the component does not use the `large` prop.

**Comment by targos** [comment]
This should be fixed by the latest blueprintjs release.

**Comment by targos** [comment]
https://github.com/palantir/blueprint/pull/7309

**Comment by stropitek** [comment]
I think we can keep this open until after they re-introduce the warning to see if they still have a bug.
